import PDFDocument from 'pdfkit';
import { Writable } from 'stream';

const PAGE_MARGIN = 40;
const TEXT = '#111827';
const MUTED = '#6B7280';
const LINE = '#E5E7EB';
const ACCENT = '#4F46E5';

export interface ReportBreakdownRow {
  label: string;
  amount: number;
  percent: number;
}

export interface ReportLineItem {
  createdAt: string;
  categoryLabel: string;
  note?: string;
  addedByName: string;
  amount: number;
}

export interface ReportResidentRow {
  name: string;
  unitNumber?: string;
  collected: boolean;
  amount: number;
}

export interface ReportResidents {
  dueAmount: number;
  dueIsSet: boolean;
  residentCount: number;
  collectedCount: number;
  expectedTotal: number;
  collectedTotal: number;
  rows: ReportResidentRow[];
}

export interface ExpenseReportData {
  buildingName: string;
  monthLabel: string;
  generatedBy: string;
  total: number;
  breakdown: ReportBreakdownRow[];
  lineItems: ReportLineItem[];
  residents?: ReportResidents;
}

interface Column {
  label: string;
  width: number;
  align?: 'left' | 'right';
}

function money(amount: number): string {
  const formatted = Number(amount || 0).toLocaleString('en-IN', {
    maximumFractionDigits: 2,
    minimumFractionDigits: 0,
  });
  return `Tk ${formatted}`;
}

function shortDate(iso: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return '';
  return date.toLocaleDateString('en-US', { day: '2-digit', month: 'short' });
}

type Doc = PDFKit.PDFDocument;

function contentWidth(doc: Doc): number {
  return doc.page.width - PAGE_MARGIN * 2;
}

function bottomLimit(doc: Doc): number {
  return doc.page.height - PAGE_MARGIN - 30;
}

function sectionTitle(doc: Doc, title: string): void {
  if (doc.y > bottomLimit(doc) - 60) doc.addPage();
  doc.moveDown(1);
  doc.fillColor(TEXT).font('Helvetica-Bold').fontSize(13).text(title, PAGE_MARGIN, doc.y);
  doc.moveDown(0.4);
}

/** Rows are a fixed height, so anything wider than its column is clipped rather than wrapped. */
function fitToWidth(doc: Doc, value: string, width: number): string {
  if (doc.widthOfString(value) <= width) return value;
  let text = value;
  while (text.length > 1 && doc.widthOfString(`${text}...`) > width) {
    text = text.slice(0, -1);
  }
  return `${text.trimEnd()}...`;
}

function drawRow(doc: Doc, columns: Column[], values: string[], bold: boolean): void {
  const height = 18;
  let x = PAGE_MARGIN;
  doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(9.5);
  const y = doc.y;

  columns.forEach((column, index) => {
    const available = column.width - 4;
    doc.text(fitToWidth(doc, values[index] ?? '', available), x + 2, y + 5, {
      width: available,
      align: column.align ?? 'left',
      lineBreak: false,
    });
    x += column.width;
  });

  doc.y = y + height;
  doc
    .moveTo(PAGE_MARGIN, doc.y)
    .lineTo(PAGE_MARGIN + contentWidth(doc), doc.y)
    .strokeColor(LINE)
    .lineWidth(0.5)
    .stroke();
}

function drawTable(doc: Doc, columns: Column[], rows: string[][]): void {
  const header = () => {
    doc.fillColor(MUTED);
    drawRow(doc, columns, columns.map((column) => column.label.toUpperCase()), true);
    doc.fillColor(TEXT);
  };

  header();
  for (const row of rows) {
    if (doc.y > bottomLimit(doc)) {
      doc.addPage();
      header();
    }
    drawRow(doc, columns, row, false);
  }
}

function summaryTile(doc: Doc, x: number, y: number, width: number, label: string, value: string): void {
  doc.roundedRect(x, y, width, 52, 8).fillColor('#F8FAFC').fill();
  doc.fillColor(MUTED).font('Helvetica').fontSize(8.5).text(label.toUpperCase(), x + 12, y + 12, {
    width: width - 24,
    lineBreak: false,
    ellipsis: true,
  });
  doc.fillColor(TEXT).font('Helvetica-Bold').fontSize(14).text(value, x + 12, y + 27, {
    width: width - 24,
    lineBreak: false,
    ellipsis: true,
  });
}

export function writeExpenseReport(target: Writable, data: ExpenseReportData): void {
  const doc = new PDFDocument({ size: 'A4', margin: PAGE_MARGIN, bufferPages: true });
  doc.pipe(target);

  doc.fillColor(ACCENT).font('Helvetica-Bold').fontSize(20).text('Society Expense Report', PAGE_MARGIN, PAGE_MARGIN);
  doc.fillColor(TEXT).font('Helvetica-Bold').fontSize(12).text(data.buildingName, { continued: false });
  doc.fillColor(MUTED).font('Helvetica').fontSize(10).text(data.monthLabel);
  doc.text(
    `Generated by ${data.generatedBy} on ${new Date().toLocaleDateString('en-US', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
    })}`,
  );

  doc.moveDown(0.8);
  const tiles: Array<[string, string]> = [['Total expenses', money(data.total)]];
  if (data.residents) {
    tiles.push(['Collected from residents', money(data.residents.collectedTotal)]);
    tiles.push([
      'Residents paid',
      `${data.residents.collectedCount} / ${data.residents.residentCount}`,
    ]);
  }

  const gap = 12;
  const tileWidth = (contentWidth(doc) - gap * (tiles.length - 1)) / tiles.length;
  const tileY = doc.y;
  tiles.forEach(([label, value], index) => {
    summaryTile(doc, PAGE_MARGIN + index * (tileWidth + gap), tileY, tileWidth, label, value);
  });
  doc.y = tileY + 52;

  sectionTitle(doc, 'Expense breakdown');
  if (data.breakdown.length) {
    drawTable(
      doc,
      [
        { label: 'Category', width: 245 },
        { label: 'Amount', width: 140, align: 'right' },
        { label: 'Share', width: 130, align: 'right' },
      ],
      data.breakdown.map((row) => [row.label, money(row.amount), `${row.percent}%`]),
    );
  } else {
    doc.fillColor(MUTED).font('Helvetica').fontSize(10).text('No expenses recorded for this month.');
    doc.fillColor(TEXT);
  }

  sectionTitle(doc, 'Line items');
  if (data.lineItems.length) {
    drawTable(
      doc,
      [
        { label: 'Date', width: 60 },
        { label: 'Category', width: 110 },
        { label: 'Note', width: 175 },
        { label: 'Added by', width: 90 },
        { label: 'Amount', width: 80, align: 'right' },
      ],
      data.lineItems.map((item) => [
        shortDate(item.createdAt),
        item.categoryLabel,
        item.note || '-',
        item.addedByName,
        money(item.amount),
      ]),
    );
  } else {
    doc.fillColor(MUTED).font('Helvetica').fontSize(10).text('No line items for this month.');
    doc.fillColor(TEXT);
  }

  if (data.residents) {
    sectionTitle(doc, 'Resident payments');
    doc.fillColor(MUTED).font('Helvetica').fontSize(9.5);
    doc.text(
      data.residents.dueIsSet
        ? `Monthly due ${money(data.residents.dueAmount)} per resident  ·  ` +
            `${money(data.residents.collectedTotal)} collected of ${money(data.residents.expectedTotal)} expected`
        : 'No monthly resident due was set for this month.',
    );
    doc.moveDown(0.4);
    doc.fillColor(TEXT);

    if (data.residents.rows.length) {
      drawTable(
        doc,
        [
          { label: '#', width: 28 },
          { label: 'Resident', width: 180 },
          { label: 'Unit', width: 72 },
          { label: 'Status', width: 95 },
          { label: 'Amount paid', width: 140, align: 'right' },
        ],
        data.residents.rows.map((row, index) => [
          String(index + 1),
          row.name,
          row.unitNumber || '-',
          row.collected ? 'Paid' : 'Pending',
          row.collected ? money(row.amount) : money(0),
        ]),
      );
    } else {
      doc.fillColor(MUTED).font('Helvetica').fontSize(10).text('No residents in this building.');
      doc.fillColor(TEXT);
    }
  }

  const range = doc.bufferedPageRange();
  for (let index = 0; index < range.count; index += 1) {
    doc.switchToPage(range.start + index);
    doc
      .fillColor(MUTED)
      .font('Helvetica')
      .fontSize(8)
      .text(
        `Page ${index + 1} of ${range.count}`,
        PAGE_MARGIN,
        doc.page.height - PAGE_MARGIN - 10,
        { width: contentWidth(doc), align: 'center', lineBreak: false },
      );
  }

  doc.end();
}

export function expenseReportFilename(buildingName: string, monthLabel: string): string {
  const slug = `${buildingName} ${monthLabel}`
    .replace(/[^a-z0-9]+/gi, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
  return `expense-report-${slug || 'society'}.pdf`;
}
